services:
  db:
    image: postgres:15
    container_name: assetflow_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  odoo:
    image: odoo:19
    container_name: assetflow_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo

volumes:
  postgres_data:
  odoo_data: